
var en = {
    Save: "Guardar",
    "Save all": "Guardar todo",
    Rename: "Renombrar",
    Open: "Abrir",
    Edit: "Editar",
    Delete: "Borrar",
    Folder: "Carpeta",
    "Add New": "Añadir nuevo",
    Size: "Tamaño",
    Date: "Fecha",
    "back to parent folder": "volver a la carpeta principal",
    Download: "Descargar",
    Type: "Escribir",
    Information: "Información",
    Files: "Archivos",
    Table: "Tabla",
    Cards: "Tarjetas",
    Total: "Total",
    "Are you sure ?": "Estás seguro ?",
    Details: "Detalles",
    "Enter a new name": "Introduce un nuevo nombre",
    Add: "Agregar",
    "Select something": "Selecciona algo",
    "Download file": "Descargar archivo",
    Preview: "Previsualizar",
    Refresh: "recargar",
    "Are you sure you want to exit without saving?": "Are you sure you want to exit without saving?",
    "Save before closing?": "Save before closing?",
    Copy: "Copy",
    Cut: "Cut",
    Paste: "Paste",
    "Deleting...": "Deleting...",
    "Copying...": "Copying...",
    "Moving...": "Moving...",
    Folders: "Folders",
    "Search results": "Search results",
    "Search results in": "Search results in",
    "Search files and folders": "Search files and folders",
    "Add new file": "Add new file",
    "Add new folder": "Add new folder",
    "Upload file": "Upload file",
    folder: "folder",
    file: "file",
    archive: "archive",
    audio: "audio",
    image: "image",
    video: "video",
    code: "code",
    document: "document",
    of: "of",
    used: "used",
    "Open item location": "Open item location",
    "Are you sure you want to delete": "Are you sure you want to delete",
    "these items:": "these items:",
    "this item:": "this item:",
    "Delete files": "Delete files",
    and: "and",
    "more file(s)": "more file(s)",
    "Close the editor": "Close the editor",
    "Close this file": "Close this file",
    "Owner": "Owner",
    "Permissions": "Permissions",
    "Change Permissions": "Change Permissions",
    "Set": "Set",
    "Extract": "Extract",
    "Extract directory": "Extract directory",
    "Extracting...": "Extracting...",
    "Compress": "Compress",
    "Compressing...": "Compressing...",
};
